package docker

import (
	"context"
	"io"

	"github.com/docker/docker/api/types"
)

// ContainerLogStream returns the logs generated by a container in an io.ReadCloser.
func (d *Docker) ContainerLogStream(name string) (io.ReadCloser, error) {
	options := types.ContainerLogsOptions{
		ShowStdout: true,
		ShowStderr: true,
		Since:      "",
		Until:      "",
		Timestamps: false,
		Follow:     true,
		Tail:       "all",
		Details:    false,
	}

	ctx := context.Background()
	reader, err := d.ContainerLogs(ctx, name, options)
	if err != nil {
		return nil, err
	}

	return reader, nil
}
